# Generated by Django 3.0.8 on 2020-07-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200709_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='static/no_image.png', null=True, upload_to='product_images', verbose_name='Изображение товара'),
        ),
    ]
