# Generated by Django 3.0.8 on 2020-08-25 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ваше имя')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст обращения')),
                ('screen', models.ImageField(blank=True, null=True, upload_to='feedback', verbose_name='Приложенное изображение')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Формы обратной связи',
            },
        ),
    ]
