# Generated by Django 3.0.8 on 2020-07-30 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_category_description'),
        ('order', '0002_auto_20200728_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_in_order', to='order.Order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_in_order', to='product.Product', verbose_name='Товар'),
        ),
    ]
