# Generated by Django 3.0.8 on 2020-08-29 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('product', '0011_category_parent_category'),
        ('order', '0003_auto_20200730_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время добавления')),
            ],
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='Cart',
        ),
        migrations.DeleteModel(
            name='ProductInOrder',
        ),
        migrations.AddField(
            model_name='productincart',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_in_cart', to='order.Cart', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='productincart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_in_cart', to='product.Product', verbose_name='Товар'),
        ),
    ]
